######################################################################
#
# File name : all_tb_compile.do
# Created on: Tue Jul 13 10:34:57 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib
D:\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
D:\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU54.srcs/sources_1/new/MULTU.v" \

D:\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU54.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU54.srcs/sources_1/ip/dist_mem_gen_0/sim/dist_mem_gen_0.v" \
"../../../CPU54.srcs/sources_1/new/ALU.v" \
"../../../CPU54.srcs/sources_1/new/RegFile.v" \
"../../../CPU54.srcs/sources_1/new/PCreg.v" \
"../../../CPU54.srcs/sources_1/new/MULT.v" \
"../../../CPU54.srcs/sources_1/new/DIVU.v" \
"../../../CPU54.srcs/sources_1/new/DIV.v" \
"../../../CPU54.srcs/sources_1/new/CP0.v" \
"../../../CPU54.srcs/sources_1/new/CPU.v" \
"../../../CPU54.srcs/sources_1/new/CLK_DIV.v" \
"../../../CPU54.srcs/sources_1/new/IMEM.v" \
"../../../CPU54.srcs/sources_1/new/DMEM.v" \
"../../../CPU54.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU54.srcs/sources_1/new/all_tb.v" \

# compile glbl module
D:\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

