######################################################################
#
# File name : all_tb_wave.do
# Created on: Fri Jul 09 01:57:30 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
