######################################################################
#
# File name : sccomp_dataflow_wave.do
# Created on: Fri Jul 09 14:44:32 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
