######################################################################
#
# File name : sccomp_dataflow_simulate.do
# Created on: Fri Jul 09 14:44:32 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L dist_mem_gen_v8_0_10 -lib xil_defaultlib xil_defaultlib.sccomp_dataflow xil_defaultlib.glbl

do {sccomp_dataflow_wave.do}

view wave
view structure
view signals

do {sccomp_dataflow.udo}

run 1000ns
