######################################################################
#
# File name : all_tb_compile.do
# Created on: Tue Jul 13 10:38:44 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
D:\\win32pe\\vlib work
D:\\win32pe\\vlib msim

D:\\win32pe\\vlib msim/xil_defaultlib

D:\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

D:\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"all_tb_time_synth.v" \
"../../../../CPU54.srcs/sources_1/new/all_tb.v" \


quit -force

