######################################################################
#
# File name : all_tb_simulate.do
# Created on: Tue Jul 13 10:38:49 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_r/0 +pulse_int_r/0 -L simprims_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.all_tb xil_defaultlib.glbl

do {all_tb_wave.do}

view wave
view structure
view signals

do {all_tb.udo}

run 5000000ns
