######################################################################
#
# File name : all_tb_wave.do
# Created on: Fri Jul 09 01:59:06 +0800 2021
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
